### ISSUE TITLE
linux kernel lichee pi zero

### ISSUE THREAD

**Issue by GastonMelo** [Unturned3/v3s3#1]
Hi, sorry to ask here but tried to ask on IRC linux-sunxi and nobody answers. Im using the lichee pi zero and tried to use the LCD TFT with drivers HX8264/HX8664 (this from aliexpress [https://es.aliexpress.com/item/33021459494.html?spm=a2g0o.order_list.0.0.21ef194diDugAP&gatewayAdapt=glo2esp](url))
I download u-boot, linux 5.2.y from github and buildroot. I can check that linux is running through urt0 but from lcd I only see the pinguin logo and nothing more, i suppose this is a driver issue but don't know how to solve it. 
On linux menuconfig i trie to look for this drivers but didn't find it:
Device Drivers --->Staging drivers --->Support for small TFT LCD display modules --->
I look for some changes on dtsi and dts for the v3s but from what i found this are ok. Maybe Im missing somehing on u-boot or buildroot but can find anything.

**Comment by Unturned3** [comment]
Hey, sorry I'm not really familiar with the graphics / display side of Linux in general. I'm afarid I cannot help you.
