### ISSUE TITLE
Openmax quality issue using ffmpeg

### ISSUE THREAD

**Issue by groove-max** [Unturned3/v3s3#2]
Hi! How did you fix image quality issue while using ffmpeg with openmax support? I have the same problem as you had:
<img width="320" alt="68747470733a2f2f77687963616e2e636f6d2f66696c65732f6d656d626572732f343633372f683236345f6261645f7175616c6974792e706e67" src="https://user-images.githubusercontent.com/68006703/201986759-4c8a490c-af26-46c2-a94a-adc2385e0a9e.png">
Thank you for help!

**Comment by Unturned3** [comment]
Hmm, interesting... Does this allow the h264 encoding quality to be adjusted via command line (i.e. via some ffmpeg option)? How does ffmpeg + openmax's memory usage look like for you?

The other reason I gave up using openmax is that it's too memory hungry. I couldn't encode anything above 640x480.

**Comment by groove-max** [comment]
Yes, it allows you to change quality via "-qp" or bitrate parameters. Without this patch the bitrate was about 200kbit/s regardless your quality/bitrate settings. The openmax is still too memory hungry, as you sad. But in my case there is enough for 640x480.
